WebApplication1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WebApplication1/Controllers/LaboratoryController.cs
using DataAccess;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ViewModel;

namespace WebApplication1.Controllers
{
    public class LaboratoryController : Controller
    {
        // GET: Laboratory
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult List()
        {
            return PartialView("_List", RincianRepo.All());
        }
        public ActionResult Create()
        {
            ViewBag.CategoryList = new SelectList(RincianRepo.AllBio(), "Id", "Name");
            return PartialView("_Create", new BiodataViewModel());
        }

        [HttpPost]
        public ActionResult Create(BiodataViewModel model)
        {

            ResponseResult result = RincianRepo.UpdateBio(model);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);

        }
        public ActionResult Detail(int Id)
        {
            List<ToolViewModel> model = RincianRepo.ByLab(Id);
            Session["Tipe"] = Id;
            return PartialView("_Detail", model);
        }

        public ActionResult DetailAlat(int Id)
        {
            List<DetailPeminjamanViewModel> model = RincianRepo.ByPeminjam(Id);
            Session["Alat"] = Id;
            return PartialView("_DetailAlat", model);
        }

        public ActionResult Data()
        {
            return PartialView("_Data", RincianRepo.AllBio());
        }

        public ActionResult CreateAlat()
        {
            ViewBag.LaboratoryList = new SelectList(RincianRepo.All(), "Id", "Name");
            ViewBag.ToolList = new SelectList(RincianRepo.ByLaboratory(0), "Id", "Name");
            return PartialView("_CreateAlat", new DetailViewModel());

        }

        public ActionResult GetByLaboratory(long laboratoryId)
        {
            return View(RincianRepo.ByLaboratory(laboratoryId));
        }

        [HttpPost]
        public ActionResult CreateAlat(DetailViewModel model)
        {

            ResponseResult result = RincianRepo.Update(model);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);

        }

        public ActionResult SelectAlat(int id)
        {
            DetailPeminjamanViewModel type = RincianRepo.ByTool(id);
            return PartialView("_SelectAlat", type);
        }

        public ActionResult Simpan(DetailViewModel model)
        {
            ResultOrder result = RincianRepo.Post(model);
            return Json(
                new
                {
                    success = result.Success,
                    message = result.Message,
                    reference = result.Reference
                }, JsonRequestBehavior.AllowGet);

        }

        public ActionResult Cek()
        {
            return PartialView("_Cek", RincianRepo.AllCek());
        }

        public ActionResult Info()
        {
            return PartialView();
        }

    }
}

WebApplication1/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WebApplication1/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebApplication1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

WebApplication1/Views/Laboratory/GetByLaboratory.cshtml
@{
    Layout = null;
}

@model IEnumerable<ViewModel.ToolViewModel>
<option value="">Select Tool</option>

@foreach (var item in Model)
{
    <option value="@item.Id">@item.Name</option>
}

WebApplication1/Views/Laboratory/Index.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <style>
        .nav-item {
            border: 2px solid #ffffff;
            border-bottom: none;
        }

        .nav-item-end {
            border: 2px solid #ffffff;
            border-bottom: 2px solid #ffffff;
        }

        .modal {
            overflow-y: auto;
        }
    </style>
</head>
<body style="background-color:lightgray">
    <div class="navbar navbar-fixed-top" style="background-color: #337ab7">
        <div class="container">
            <div class="navbar-collapse collapse">
                <div class="headerrole">
                    <div class="navbar-header text-center col-md-12">
                        <h3>
                            <b>
                                <font color="White">
                                    Peminjaman Alat Laboratorium Fisika
                                </font>
                            </b>
                        </h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="body center-block">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-2 col-sm-offset-1" style="margin-top:2%">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="btn btn-primary btn-labor" href="#">Laboratorium</a>
                        </li>
                        <li class="nav-item">
                            <a class="btn btn-primary btn-data" href="#">Peminjaman</a>
                        </li>
                        <li class="nav-item">
                            <a class="btn btn-primary btn-cek" href="#">Cek Peminjaman</a>
                        </li>
                        <li class="nav-item-end">
                            <a class="btn btn-primary btn-infor" href="#">Informasi</a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-8" style="background-color:white;height:400px;width:700px;margin-top:2%">
                    <div class="place-index"></div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

<script type="text/javascript">
    $(".btn-labor").click(function () {
        $.ajax({
            url: '@Url.Action("List","Laboratory")',
            type: 'get',
            success: function (result) {
                $(".place-index").html(result);
            }
        });
        });

        $(".btn-data").click(function () {
        $.ajax({
            url: '@Url.Action("Create","Laboratory")',
            type: 'get',
            success: function (result) {
                $(".place-index").html(result);
            }
        });
        });

    function GetList() {
                $.ajax({
                url: '@Url.Action("Data","Laboratory")',
                type: 'get',
                success: function (result) {
                $(".place-index").html(result);
                }
         });
    }

        $(".btn-cek").click(function () {
        $.ajax({
            url: '@Url.Action("Cek","Laboratory")',
            type: 'get',
            success: function (result) {
                $(".place-index").html(result);
            }
        });
        });

    
        $(".btn-infor").click(function () {
        $.ajax({
            url: '@Url.Action("Info","Laboratory")',
            type: 'get',
            success: function (result) {
                $(".place-index").html(result);
            }
        });
        });



</script>

WebApplication1/Views/Laboratory/Info.cshtml
    <div class="panel-group">
        <div class="tab-content" style="border-bottom:solid; border-bottom-color:#337ab7;">
            <div class="row" style="background-color:#337ab7">
                <h4 style="color: white; margin-left: 20px">INFORMASI</h4>
            </div>
            <br />
            <p>Prosedur Peminjaman</p>
            <p>1. Cek alat yang tersedia di setiap Laboratorium pada Menu "Laboratorium"</p>
            <p>2. Isi data diri beserta alat yang akan dipinjam pada Menu "Peminjaman"</p>
            <p>3. Pantau proses peminjaman pada menu "Cek Peminjaman"</p>
            <p>4. Jika pada keterangan tertulis "Telah Diproses", maka mahasiswa dapat mendatangi labor untuk pengambilan alat</p>
            <p>5. Jika dalam waktu +48 jam keterangan masih "Belum Diproses", Hubungi(WA): (+62)81316143848 (Tandini)</p>
            <p></p>
            <p></p>
            <p>NB: Sebaiknya peminjaman dilakukan 1 minggu sebelum kebutuhan pemakaian alat</p>
        </div>
    </div>

WebApplication1/Views/Laboratory/_Cek.cshtml
@model IEnumerable<ViewModel.DetailPeminjamanViewModel>

<div class="panel-group">
    <div class="tab-content">
        <div class="row" style="background-color:#337ab7">
            <h4 style="color: white; margin-left: 20px">CEK PEMINJAMAN</h4>
        </div>
        <br />

        <table class="table table-striped">
            <tr>
                <th style="width:30%;">
                    Nama
                </th>
                <th style="width:20%;">
                    No.Bp
                </th>
                <th style="width:30%;">
                    Laboratorium
                </th>
                <th style="width:20%;">
                    Alat
                </th>
                <th style="width:30%;">
                    Keterangan
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Bio)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NoBp)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NameLab)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Keterangan)
                    </td>

                </tr>
            }

        </table>
    </div>
</div>

WebApplication1/Views/Laboratory/_Create.cshtml
@model ViewModel.BiodataViewModel

@using (Html.BeginForm("Create", "Laboratory", FormMethod.Post, new { id = "form-create", name = "form-create" }))
{
    @Html.AntiForgeryToken()

    <div class="panel-group">
        <div class="tab-content" style="border-bottom:solid; border-bottom-color:#337ab7;">
            <div class="row" style="background-color:#337ab7">
                <h4 style="color: white; margin-left: 20px">PEMINJAMAN</h4>
            </div>
            <br />
            <div class="form-group">
                <div class="row">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Id)
                    <div class="col-sm-4" style="margin-left:5%;">
                        <label>Nama*</label>
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-4" style="margin-left:5%;">
                        <label>No.Bp*</label>
                        @Html.EditorFor(model => model.Bp, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Bp, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-3" style="margin-left:5%; margin-top:3%;">
                        <input type="submit" value="Simpan" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<div />

<script type="text/javascript">
    $("#form-create").submit(function () {
        $.ajax({
            url: this.action,
            type: this.method,
            data: $(this).serialize(),
            success: function (result) {
                if (result.success) {
                    GetList();
                } else {
                    alert("error! " + result.message);
                }
            }
        });
        return false;
    });

</script>

WebApplication1/Views/Laboratory/_CreateAlat.cshtml
@model ViewModel.DetailViewModel


@Html.AntiForgeryToken()

<div class="form-horizontal">

    <div class="form-group">
        <div class="row">
            <div class="col-sm-5" style="margin-left: 5%;">
                <label>Tgl. Peminjaman*</label>
                <input type="date" class="form-control test_date" id="awal" name="awal" value="">
                <span class="text-danger" id="test_error"></span>
            </div>
            <div class="col-sm-5">
                <label>Tgl. Pengembalian*</label>
                <input type="date" class="form-control expired_test" id="akhir" name="akhir">
                <span class="text-danger" id="ex_error"></span>
                <small class="form-text text-muted Validation" id="Validation" style="display:none; color:red;">Tanggal Peminjaman tidak boleh kurang dari tanggal Pengembalian</small>
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="row">
            <div class="col-sm-4" style="margin-left: 5%;">
                <label>Laboratorium</label>
                @Html.DropDownListFor(model => model.LaboratoryId, (IEnumerable<SelectListItem>)ViewBag.LaboratoryList,
     "Select Laboratory", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LaboratoryId, "", new { @class = "text-danger" })
            </div>
            <div class="col-sm-4">
                <label>Alat</label>
                @Html.DropDownListFor(model => model.ToolId, (IEnumerable<SelectListItem>)ViewBag.ToolList,
"Select Tool", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ToolId, "", new { @class = "text-danger" })
            </div>
            <div class="col-sm-3" style="margin-top: 3.7%;">
                <button type="button" class="btn btn-primary btn-pilih" title="Pilih">Pilih</button>
            </div>
        </div>
    </div>

    <div class="panel-body">
        <table class="table table-bordered table-striped" id="test-table">
            <thead>
                <tr>
                    <th style="width: 40%">Laboratorium</th>
                    <th style="width: 40%">Alat</th>
                    <th style="width: 20%">#</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>

    <div class="row">
        <div class="col-lg-10">
            <div class="col-md-offset-4 col-md-7">
                <button class="btn btn-warning" id="batal">Batal</button>
                <button value="Simpan" id="btn-save" class="btn btn-primary" style="margin-right: 5%;">Simpan</button>
            </div>
        </div>
    </div>

</div>


<script type="text/javascript">

    $("#akhir").change(function () {
            var exdate = $("#akhir").val();
            var strdate = $("#awal").val();
            if (exdate < strdate) {
                $("#Validation").show();
            }
            else {
                $("#Validation").hide();
            }
        });

        $("#awal").change(function () {
            var exdate = $("#akhir").val();
            var strdate = $("#awal").val();
            if (exdate < strdate && exdate != "") {
                $("#Validation").show();
            }
            else {
                $("#Validation").hide();
            }
        });

    $("#LaboratoryId").change(function () {
        $.ajax({
            url: '@Url.Action("GetByLaboratory","Laboratory")',
            type: 'get',
            data: { LaboratoryId: $(this).val() },
            success: function (result) {
                $("#ToolId").html(result);
            }
        });
    });

    $(".btn-pilih").click(function () {
        $.ajax({
            url: '@Url.Action("SelectAlat","Laboratory")',
            type: 'get',
            data: { id: $(this).attr("value") },
            success: function (result) {
                $("#test-table tbody").append(result);
            }
        });
    });

     $("#ToolId").change(function () {
        var test = $("#ToolId").val();
        $(".btn-pilih").attr("value", test);
    })
    $("#LaboratoryId").change(function () {
        var test = $("#LaboratoryId").val();
        $(".btn-pilih").attr("value", test);
    })

             function Remove(obj) {
            var tr = $(obj).closest('tr');
                tr.remove();
        }

 var data = {};
    $("#btn-save").click(function () {
            var str = $("#awal").val();
            var fnl = $("#akhir").val();
            var details = [];
            $("#test-table tbody").find("tr").each(function () {
                var Id = $(this).find("input[name=Id]").val();
                detail = {
                    ToolId: Id,
                };
                details.push(detail);
            });

            data = {
                awal: $("#awal").val(),
                akhir: $("#akhir").val(),
                biodataId: kl,
                detail: details
            }
        $.ajax({
            url: '@Url.Action("Simpan", "Laboratory")',
            type: 'post',
            data: { model: data },
            success: function (result) {
                if (result.success) {
                    $("#exampleCreate").modal("hide");
                }
                else {
                    alert("Error:\n" + result.message);
                }
            }
        });
    });

         $("#batal").click(function () {
        $("#exampleCreate").modal("hide");
    });

</script>

WebApplication1/Views/Laboratory/_Data.cshtml
@model IEnumerable<ViewModel.BiodataViewModel>

    <div class="panel-group">
        <div class="tab-content">
            <div class="row" style="background-color:#337ab7">
                <h4 style="color: white; margin-left: 20px">Data Peminjaman</h4>
            </div>
            <br />

            <style>
                table {
                    font-family: Aria l, sans-serif;
                    border-collapse: collapse;
                    width: 100%;
                }

                td, th {
                    text-align: left;
                    padding: 15px;
                }

                td {
                    text-align: left;
                    padding: 15px;
                }

                tr:nth-child(even) {
                    background-color: #dddddd;
                }
            </style>

            <div class="col-12">
                <table class="table">
                    <tr>
                        <th>
                            NAMA
                        </th>
                        <th>
                            NO.BP
                        </th>
                        <th>
                            #
                        </th>
                    </tr>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Bp)
                            </td>
                            <td>
                                <div class="btn-group btn-group-sm">
                                    <button type="button" class="btn btn-warning btn-pinjam" data-id="@item.Id" title="Pinjam">Pinjam</button>
                                    <button type="button" class="btn btn-danger btn-detailAlat" data-id="@item.Id" title="Detail">Detail</button>
                                    <button type="button" class="btn btn-success btn-selesai" data-id="@item.Id" title="Delete">Selesai</button>
                                </div>
                            </td>
                        </tr>
                    }

                </table>
            </div>
        </div>

        <div class="modal fade" id="exampleCreate" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header bg-primary header-modal-sm">
                        <h4 class="modal-title modal-title-create">Modal title</h4>
                    </div>
                    <div class="modal-body modal-create">
                        <p>One fine body&hellip;</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

        <script type="text/javascript">

            var kl;
            $(".btn-pinjam").click(function () {
             kl = $(this).attr("data-id");
            $.ajax({
                url: '@Url.Action("CreateAlat", "Laboratory")',
                type: 'get',
                data: { id: $(this).attr("data-id")},
                success: function (result) {
                    $(".header-modal-sm").css("background-color", "#337ab7");
                    $(".modal-title-create").html("Pinjam Alat");
                    $(".modal-create").html(result);
                    $("#exampleCreate").modal("show");
                }
            });
        });

    var idAlat;
            $(".btn-detailAlat").click(function () {
        idAlat = $(this).attr("data-id");
        $.ajax({
            url: '@Url.Action("DetailAlat", "Laboratory")',
            type: 'get',
            data: { id: idAlat },
            success: function (result) {
                $(".header-modal-sm").css("background-color", "#337ab7");
                $(".modal-title-create").html("Detail Peminjaman");
                $(".modal-create").html(result);
                $("#exampleCreate").modal("show");
            }
        });
    });

            $(".btn-selesai").click(function () {
            window.location.reload();
        });
            
        </script>

WebApplication1/Views/Laboratory/_DeleteAlat.cshtml
@model ViewModel.DetailPeminjamanViewModel

<div class="panel-heading">
    <div class="col-md-3" style="color:red; margin-left:20%; margin-top:2%; font-size: 80px;">
        <span class="glyphicon glyphicon-trash"></span>
    </div>
    <br />
    <div class="col-md-12" style="color:red; margin-top:2%; margin-left:10%;">
        <span>Apakah anda yakin ingin menghapus Alat?</span>
        <br />
    </div>
</div>
<div>
    @using (Html.BeginForm("DeleteAlat", "Laboratory", FormMethod.Post,
            new { id = "form-delete", name = "form-delete" }))
    {
        <div class="form-horizontal">
            @Html.HiddenFor(model => model.Id)

            <div class="form-group">
                <div class="col-md-offset-3 col-md-10" style="margin-top:5%;">
                    <input type="button" value="batal" class="btn btn-warning btn-batal" />
                    <input type="submit" value="Ya" class="btn btn-danger btn-ya" />
                </div>
            </div>
        </div>
    }

</div>

<script type="text/javascript">
    $("#form-delete").submit(function () {
        $.ajax({
            url: this.action,
            type: this.method,
            data: $(this).serialize(),
            success: function (result) {
                if (result.success) {
                    $("#exampleDelete").modal("hide");
                    GetList();
                    GetAlat();
                } else {
                    alert("error! " + result.message);
                }
            }
        });
        return false;
    });
    $(".btn-batal").on("click", function () {
        $("#exampleDelete").modal("hide");
    });
</script>

WebApplication1/Views/Laboratory/_Detail.cshtml
@model IEnumerable<ViewModel.ToolViewModel>


<table class="table table-striped">
    <tr>
        <th style="width:40%;">
            Alat
        </th>
        <th style="width:20%;">
            Jumlah
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Jumlah)
            </td>
        </tr>
    }

</table>

<div class="row">
    <div class="col-lg-10">
        <div class="col-md-offset-11 col-md-7">
            <button id="btn-kembali" class="btn btn-warning">Kembali</button>
        </div>
    </div>
</div>

<script type="text/javascript">

     $("#btn-kembali").click(function () {
        $("#exampleLabor").modal("hide");
    });

</script>

WebApplication1/Views/Laboratory/_DetailAlat.cshtml
@model IEnumerable<ViewModel.DetailPeminjamanViewModel>


<table class="table table-striped">
    <tr>
        <th style="width:20%;">
            Alat
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
        </tr>
    }

</table>

<div class="row">
    <div class="col-lg-10">
        <div class="col-md-offset-11 col-md-7">
            <button id="btn-kembali" class="btn btn-warning">Kembali</button>
        </div>
    </div>
</div>

<div class="modal fade" id="exampleDelete" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header bg-primary header-modal-delete">
                <h4 class="modal-title modal-title-delete">Modal title</h4>
            </div>
            <div class="modal-body modal-delete">
                <p>One fine body&hellip;</p>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

     $("#btn-kembali").click(function () {
         $("#exampleCreate").modal("hide");
     });

</script>

WebApplication1/Views/Laboratory/_List.cshtml
@model IEnumerable<ViewModel.LaboratoryViewModel>

<div class="panel-group">
    <div class="tab-content">
        <div class="row" style="background-color:#337ab7">
            <h4 style="color: white; margin-left: 20px">LABORATORIUM</h4>
        </div>
        <br />

        <style>
            table {
                font-family: Aria l, sans-serif;
                border-collapse: collapse;
                width: 100%;
            }

            td, th {
                text-align: left;
                padding: 15px;
            }

            td {
                text-align: left;
                padding: 15px;
            }

            tr:nth-child(even) {
                background-color: #dddddd;
            }
        </style>

        <div class="col-12">
            <table class="table">
                <tr>
                    <th>
                        Laboratorium
                    </th>
                    <th>
                        Initial
                    </th>
                    <th>
                        #
                    </th>
                </tr>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Initial)
                        </td>
                        <td>
                            <div class="btn-group btn-group-sm">
                                <button type="button" class="btn btn-danger btn-detail" data-id="@item.Id" title="Detail">Detail</button>
                            </div>
                        </td>
                    </tr>
                }

            </table>
        </div>
    </div>
</div>

<div class="modal fade" id="exampleLabor" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header bg-primary header-modal-sm">
                <h4 class="modal-title modal-title-labor">Modal title</h4>
            </div>
            <div class="modal-body modal-labor">
                <p>One fine body&hellip;</p>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    $(".btn-detail").click(function () {
        $.ajax({
            url: '@Url.Action("Detail", "Laboratory")',
            type: 'get',
            data: { id: $(this).attr("data-id")},
            success: function (result) {
                $(".header-modal-sm").css("background-color", "#337ab7");
                $(".modal-title-labor").html("Detail Alat");
                $(".modal-labor").html(result);
                $("#exampleLabor").modal("show");
            }
        });
    });

</script>